name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - run: |
        chmod +x ./build.sh
        ./build.sh
    - uses: actions/upload-artifact@v3
      with:
        name: asdfg
        path: safetynet-fix-*.zip
